language: haskell
before_install:
  - cabal update
  - travis/cabal-apt-install $mode

install:
  - cabal install $mode --only-dependencies --force-reinstalls --constraint="template-haskell == 2.7.0.0"
  - cabal configure -ferror
  - cabal build

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
