language: haskell
before_install:
  - cabal install hlint
  - travis/cabal-apt-install $mode

install:
  - cabal configure $mode
  - cabal build

script:
  - hlint -c . --ignore="Parse error" && cabal test

env:
  - mode="--enable-tests -ferror" script="cabal test --show-details=always"
