env:
 - GHCVER=7.8.2 # see note about Alex/Happy

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]; then
     travis_retry sudo apt-get install happy-1.19.3 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

install:
 - cabal update
 - cabal install --only-dependencies -ftests --enable-tests --enable-benchmarks

script:
 - cabal configure -ftests --enable-tests --enable-benchmarks --enable-library-coverage -v2
 - cabal build
 - run-cabal-test
 - cabal check
 - cabal sdist

 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

after_script:
  - hpc-coveralls io-machines
  - hpc-coveralls functional
