language: haskell
before_install:
  - cabal install hpc-coveralls

install:
  - cabal install --only-dependencies $mode

script:
  - cabal configure $mode
  - run-cabal-test

after_script:
  - hpc-coveralls functional
  - hpc-coveralls io-machines

env:
  - mode="--enable-tests -ftests --enable-library-coverage"
