language: haskell
before_install:
  - travis/cabal-apt-install $mode

install:
  - cabal configure $mode
  - cabal build

env:
  - mode="--enable-tests -ferror" script="cabal test --show-details=always"
