language: haskell
before_install:
  - travis/cabal-apt-install $mode

install:
  - cabal configure -ferror $mode
  - cabal build

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
