language: haskell
before_install:
  - cabal install hlint
  - travis/cabal-apt-install $mode

install:
  - cabal configure $mode
  - cabal build

script:
  - hlint -c . --ignore="Parse error"
  - cabal test --show-details=always

env:
  - mode="--enable-tests -ferror"
