language: haskell
before_install:
  - while true; do if cabal install hlint; then break; fi; done
  - while true; do if travis/cabal-apt-install $mode; then break; fi; done

install:
  - cabal configure $mode
  - cabal build

script:
  - hlint -c . --ignore="Parse error"
  - cabal test --show-details=always

env:
  - mode="--enable-tests -ferror"
